# Generated by Django 5.2 on 2025-04-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangBMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True, verbose_name='Kode Barang')),
                ('uraian_barang', models.TextField(verbose_name='Uraian Barang')),
                ('nup', models.IntegerField(verbose_name='Nomor Urut Pendaftaran (NUP)')),
                ('nilai_perolehan', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Nilai Perolehan')),
                ('tahun_perolehan', models.IntegerField(verbose_name='Tahun Perolehan')),
                ('masa_manfaat_standar', models.PositiveIntegerField(help_text='Umur ekonomis standar aset dalam tahun.', verbose_name='Masa Manfaat Standar (Tahun)')),
            ],
            options={
                'verbose_name': 'Barang BMN',
                'verbose_name_plural': 'Daftar Barang BMN',
                'ordering': ['kode_barang', 'nup'],
            },
        ),
        migrations.CreateModel(
            name='RencanaPemanfaatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_rencana', models.IntegerField(verbose_name='Tahun Rencana')),
                ('jenis_pemanfaatan', models.CharField(choices=[('SEWA', 'Sewa'), ('PINJAM_PAKAI', 'Pinjam Pakai'), ('BGS_BSG', 'BGS/BSG (Bangun Guna Serah/Bangun Serah Guna)'), ('KETUPI', 'KETUPI (Kerjasama Penyediaan Infrastruktur)')], max_length=20, verbose_name='Jenis Pemanfaatan')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='rencana_bmn.barangbmn')),
            ],
            options={
                'verbose_name': 'Rencana Pemanfaatan',
                'verbose_name_plural': 'Rencana Pemanfaatan',
                'ordering': ['tahun_rencana', 'barang'],
                'abstract': False,
                'unique_together': {('barang', 'tahun_rencana')},
            },
        ),
        migrations.CreateModel(
            name='RencanaPemindahtanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_rencana', models.IntegerField(verbose_name='Tahun Rencana')),
                ('jenis_pemindahtanganan', models.CharField(choices=[('LELANG', 'Penjualan dengan Lelang'), ('HIBAH', 'Hibah'), ('TUKAR_MENUKAR', 'Tukar Menukar')], max_length=20, verbose_name='Jenis Pemindahtanganan')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='rencana_bmn.barangbmn')),
            ],
            options={
                'verbose_name': 'Rencana Pemindahtanganan',
                'verbose_name_plural': 'Rencana Pemindahtanganan',
                'ordering': ['tahun_rencana', 'barang'],
                'abstract': False,
                'unique_together': {('barang', 'tahun_rencana')},
            },
        ),
        migrations.CreateModel(
            name='RencanaPenggunaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_rencana', models.IntegerField(verbose_name='Tahun Rencana')),
                ('jenis_penggunaan', models.CharField(choices=[('SENDIRI', 'Digunakan Sendiri'), ('PIHAK_LAIN', 'Digunakan Pihak Lain')], max_length=20, verbose_name='Jenis Penggunaan')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='rencana_bmn.barangbmn')),
            ],
            options={
                'verbose_name': 'Rencana Penggunaan',
                'verbose_name_plural': 'Rencana Penggunaan',
                'ordering': ['tahun_rencana', 'barang'],
                'abstract': False,
                'unique_together': {('barang', 'tahun_rencana')},
            },
        ),
        migrations.CreateModel(
            name='RencanaPenghapusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_rencana', models.IntegerField(verbose_name='Tahun Rencana')),
                ('jenis_penghapusan', models.CharField(choices=[('LELANG', 'Penjualan dengan Lelang'), ('HIBAH', 'Hibah'), ('TUKAR_MENUKAR', 'Tukar Menukar'), ('SEBAB_LAIN', 'Sebab-Sebab Lain')], max_length=20, verbose_name='Jenis/Alasan Penghapusan')),
                ('keterangan_sebab_lain', models.TextField(blank=True, null=True, verbose_name='Keterangan Sebab Lain')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='rencana_bmn.barangbmn')),
            ],
            options={
                'verbose_name': 'Rencana Penghapusan',
                'verbose_name_plural': 'Rencana Penghapusan',
                'ordering': ['tahun_rencana', 'barang'],
                'abstract': False,
                'unique_together': {('barang', 'tahun_rencana')},
            },
        ),
    ]
