# Generated by Django 5.2 on 2025-04-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rencana_bmn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPerubahanRencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('aksi', models.CharField(choices=[('UBAH', 'Perubahan Data'), ('BATAL', 'Pembatalan Rencana')], max_length=10, verbose_name='Jenis Aksi')),
                ('alasan', models.TextField(verbose_name='Alasan Perubahan/Pembatalan')),
                ('tanggal_aksi', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Aksi')),
                ('status_proses', models.CharField(choices=[('BERHASIL', 'Berhasil Diproses'), ('GAGAL', 'Gagal Diproses')], default='BERHASIL', max_length=10, verbose_name='Status Proses')),
                ('detail_sebelum', models.JSONField(blank=True, null=True, verbose_name='Data Sebelum')),
                ('detail_sesudah', models.JSONField(blank=True, null=True, verbose_name='Data Sesudah')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_perubahan', to='rencana_bmn.barangbmn')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('rencanapenggunaan', 'rencanapemanfaatan', 'rencanapemindahtanganan', 'rencanapenghapusan')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Pelaksana')),
            ],
            options={
                'verbose_name': 'Log Perubahan Rencana',
                'verbose_name_plural': 'Log Perubahan Rencana',
                'ordering': ['-tanggal_aksi'],
            },
        ),
    ]
