# Generated by Django 5.2 on 2025-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencana_bmn', '0002_logperubahanrencana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbmn',
            name='kode_barang',
            field=models.CharField(max_length=50, verbose_name='Kode Barang'),
        ),
        migrations.AlterField(
            model_name='barangbmn',
            name='masa_manfaat_standar',
            field=models.PositiveIntegerField(help_text='Umur ekonomis standar aset dalam tahun (0 jika tidak disusutkan).', verbose_name='Masa Manfaat Standar (Tahun)'),
        ),
        migrations.AlterField(
            model_name='rencanapemanfaatan',
            name='jenis_pemanfaatan',
            field=models.CharField(choices=[('SEWA', 'Sewa'), ('PINJAM_PAKAI', 'Pinjam Pakai'), ('BGS_BSG', 'BGS/BSG'), ('KETUPI', 'KETUPI')], max_length=20, verbose_name='Jenis Pemanfaatan'),
        ),
        migrations.AlterUniqueTogether(
            name='barangbmn',
            unique_together={('kode_barang', 'nup')},
        ),
    ]
